FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY backend/pom.xml .
COPY backend/src ./src

RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-jammy
WORKDIR /work/

COPY --from=build /app/target/quarkus-app/ /work/

EXPOSE 8080
ENV QUARKUS_HTTP_HOST=0.0.0.0
CMD ["java", "-jar", "/work/quarkus-run.jar"]